# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Mathieu Claviere, PhD
title: Marketing et transformation digitale
email: contact@mathieuclaviere.com
website: mathieuclaviere.com

# Social links
twitter_username: m_clvr
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mathieu_clvr
linkedin_username: mathieuclaviere
# youtube_username: globalmtb


# About Section
about_title: A propos de moi 
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>



# Experience Section
experience_title: Experiences professionnelles

# Education Section
ducaton_title: Education

# Projects Section
projects_title: compétences

# More Section
more_title: Centre d'intérêts 
more_content: | # this will include new lines to allow paragraphs
    <b>Sports:</b> course à pied en compétition (trail, semi-marathon), randonnée  

    <b>Voyages autonomes:</b> Japon, Kirghizistan, Inde, Israel, Jordanie, Thaïlande, Maroc, Italie, Irlande, Grèce, Espagne, Madère, Turquie  
   
    <b>Photographie et technologies digitales:</b> développement technique et éditorial du site web de voyage (capturexplore.com) : Implémentation de Wordpress, rédaction des articles, traitement des photos via Adobe Lightroom, Search Engine Optimisation


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
