# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Mathieu Claviere, PhD
title: Marketing et transformation digitale
email: contact@mathieuclaviere.com
website: mathieuclaviere.com

# Social links
twitter_username: m_clvr
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mathieu_clvr
linkedin_username: mathieuclaviere
# youtube_username: globalmtb


# About Section
about_title: À propos de moi 
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Bonjour! Je m'appelle Mathieu Claviere, je suis titulaire d'un doctorat en infectiologie, ma thèse m'a permis de manager un projet durant trois ans. Mes missions consistaient principalement à designer des hypothèses, à mettre en oeuvre les expérimentations en résultant, puis à réaliser des analyses statistiques sur les données acquises.

  Je possède également une seconde compétence en marketing et transformation digitale que j'ai acquise en mastère spécialisé au sein d'EM Lyon Business school puis en tant qu'assistant marketing digital au sein du groupe Urgo.

  Passionné depuis toujours par les nouvelles technologies et fort de mes expertises en <mark>gestion de projet</mark>, <mark>analyse de données</mark> et <mark>marketing digital</mark> acquises au cours de mes expériences, j'axe mon projet professionnel autour de la transformation digitale des entreprises.



# Experience Section
experience_title: Experiences professionnelles

# Education Section
ducaton_title: Education

# Projects Section
projects_title: Compétences

# More Section
more_title: Centres d'intérêts 
more_content: | # this will include new lines to allow paragraphs
    <b>Sports:</b> course à pied en compétition (trail, semi-marathon), randonnée  

    <b>Voyages autonomes:</b> Japon, Kirghizistan, Inde, Israel, Jordanie, Thaïlande, Maroc, Italie, Irlande, Grèce, Espagne, Madère, Turquie  
   
    <b>Photographie et technologies digitales:</b> développement technique et éditorial du site web de voyage [capturexplore.com](capturexplore.com): Implémentation de Wordpress, rédaction des articles, traitement des photos via Adobe Lightroom, Search Engine Optimisation


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
